### ISSUE TITLE
Oppressed workers already capitalized

### ISSUE THREAD

**Issue by iambryanhaney** [learn-co-curriculum/ruby-enumerables-each-the-unexpressive-enumerable#3]
To illustrate the work being done, the initial names should not be capitalized...

`oppressed_workers = ["Dopey", "Sneezy", "Happy", "Angry", "Doc", "Lemonjello", "Sleepy" ]`
`oppressed_workers.each do |oppressed_worker|`
`   puts "#{oppressed_worker.capitalize} wants to start a union!"`
`end #=>`
`# Dopey wants to start a union!`
`....`

**Comment by maxwellbenton** [comment]
Hi @iambryanhaney,

Thank you for spotting this and providing feedback! We've updated the code snippet so that the original string names are no longer capitalized, which should resolve this issue.
